/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CoreError } from './core-error';
// May contain unused imports in some cases
// @ts-ignore
import type { MxDetails } from './mx-details';

/**
 * @type CheckEmailOutputMx
 * Details obtained from querying the mail server\'s MX records.
 * @export
 */
export type CheckEmailOutputMx = CoreError | MxDetails;


