/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Enumeration describing the method used to verify Hotmail B2C emails.
 * @export
 * @enum {string}
 */

export const HotmailB2CVerifMethod = {
    Smtp: 'Smtp',
    Headless: 'Headless'
} as const;

export type HotmailB2CVerifMethod = typeof HotmailB2CVerifMethod[keyof typeof HotmailB2CVerifMethod];



