/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Results from SMTP connection attempts to the mail server.
 * @export
 * @interface SmtpDetails
 */
export interface SmtpDetails {
    /**
     * Indicates if the mail exchanger can be contacted successfully.
     * @type {boolean}
     * @memberof SmtpDetails
     */
    'can_connect_smtp': boolean;
    /**
     * Indicates if the mailbox is full.
     * @type {boolean}
     * @memberof SmtpDetails
     */
    'has_full_inbox': boolean;
    /**
     * Indicates if the email address is a catch-all address.
     * @type {boolean}
     * @memberof SmtpDetails
     */
    'is_catch_all': boolean;
    /**
     * Indicates if an email sent to this address is deliverable.
     * @type {boolean}
     * @memberof SmtpDetails
     */
    'is_deliverable': boolean;
    /**
     * Indicates if the email address has been disabled by the provider.
     * @type {boolean}
     * @memberof SmtpDetails
     */
    'is_disabled': boolean;
}

