/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Validation of the email address syntax.
 * @export
 * @interface SyntaxDetails
 */
export interface SyntaxDetails {
    /**
     * The domain part of the email address.
     * @type {string}
     * @memberof SyntaxDetails
     */
    'domain': string;
    /**
     * Indicates if the email address syntax is valid.
     * @type {boolean}
     * @memberof SyntaxDetails
     */
    'is_valid_syntax': boolean;
    /**
     * The username part of the email address.
     * @type {string}
     * @memberof SyntaxDetails
     */
    'username': string;
}

