/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Webhook } from './webhook';

/**
 * Optional webhook configuration for sending email verification results during bulk verification.
 * @export
 * @interface TaskWebhook
 */
export interface TaskWebhook {
    /**
     * 
     * @type {Webhook}
     * @memberof TaskWebhook
     */
    'on_each_email'?: Webhook;
}

