/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The method used for email verification.
 * @export
 * @interface VerifMethod
 */
export interface VerifMethod {
    /**
     * The method used for the email verification.
     * @type {string}
     * @memberof VerifMethod
     */
    'type': VerifMethodTypeEnum;
}

export const VerifMethodTypeEnum = {
    Smtp: 'Smtp',
    Headless: 'Headless',
    Api: 'Api',
    Skipped: 'Skipped'
} as const;

export type VerifMethodTypeEnum = typeof VerifMethodTypeEnum[keyof typeof VerifMethodTypeEnum];


